name: build-devices

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    devices:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-13]
                device: [ios, tvos, watchos]
        steps:
            -   uses: actions/checkout@v2
            -   name: build
                run: |
                    swift --version
                    xcrun xcodebuild -list
                    xcrun xcodebuild build -scheme "PNG" -destination "generic/platform=${{ matrix.device }}"
